import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";

export const runtime = "nodejs";

export async function POST(request: Request) {
  let body: any;
  try {
    body = await request.json();
  } catch (error) {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const locale = body?.locale === "zh" ? "zh" : "en";
  const title: string = body?.title || (locale === "zh" ? "SeeQi 综合报告" : "SeeQi Insight Report");
  const reportId: string = body?.reportId || "unknown";
  const generatedAt: string = body?.generatedAt || new Date().toISOString();
  const sections: Array<{ heading: string; items?: string[]; description?: string }> = Array.isArray(body?.sections)
    ? body.sections
    : [];
  const highlights: string[] = Array.isArray(body?.highlights) ? body.highlights : [];

  const doc = new PDFDocument({ size: "A4", margin: 48 });
  const chunks: Uint8Array[] = [];
  doc.on("data", (chunk) => chunks.push(chunk));

  const bufferPromise = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  doc.fontSize(20).fillColor("#234").text(title, { align: "left" });
  doc.moveDown(0.25);
  doc.fontSize(11).fillColor("#4a5c5a");
  doc.text(`${locale === "zh" ? "报告编号" : "Report ID"}: ${reportId}`);
  doc.text(`${locale === "zh" ? "生成时间" : "Generated"}: ${new Date(generatedAt).toLocaleString(locale === "zh" ? "zh-CN" : "en-US", { hour12: false })}`);

  if (highlights.length) {
    doc.moveDown(1);
    doc.fontSize(14).fillColor("#234").text(locale === "zh" ? "核心亮点" : "Key Highlights");
    doc.moveDown(0.4);
    doc.fontSize(11).fillColor("#333");
    highlights.forEach((item) => {
      doc.circle(doc.x + 3, doc.y + 5, 2).fill("#4a7157");
      doc.fillColor("#333").text(`   ${item}`, { continued: false });
      doc.moveDown(0.2);
    });
  }

  sections.forEach((section) => {
    doc.moveDown(1);
    if (section.heading) {
      doc.fontSize(13).fillColor("#234").text(section.heading);
    }
    if (section.description) {
      doc.moveDown(0.2);
      doc.fontSize(11).fillColor("#3c4d4a").text(section.description, { align: "left" });
    }
    if (Array.isArray(section.items) && section.items.length > 0) {
      doc.moveDown(0.3);
      doc.fontSize(11).fillColor("#333");
      section.items.forEach((item) => {
        doc.circle(doc.x + 3, doc.y + 5, 2).fill("#8dae92");
        doc.fillColor("#333").text(`   ${item}`);
        doc.moveDown(0.15);
      });
    }
  });

  doc.moveDown(1.5);
  doc.fontSize(10).fillColor("#60706d").text(
    locale === "zh"
      ? "此报告由 SeeQi AI 生成，仅供文化娱乐与健康参考，不替代医生诊断。"
      : "This report is generated by SeeQi AI and is intended for cultural and wellness reference only."
  );
  doc.end();

  let pdfBuffer: Buffer;
  try {
    pdfBuffer = await bufferPromise;
  } catch (error) {
    console.error("report-export-pdf", error);
    return NextResponse.json({ error: "Failed to generate PDF" }, { status: 500 });
  }

  return new NextResponse(pdfBuffer, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="seeqi-report-${reportId}.pdf"`,
      "Content-Length": pdfBuffer.length.toString(),
    },
  });
}






